In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
import nltk
from nltk.corpus import stopwords
import string


In [2]:
#nltk.download()

In [3]:
Data = pd.read_table('C:/Users/91805/Documents/Kalpesh Mahajan/Natuaral Language Processing Class/sms.tsv',header=None,
                     names=['Classification','Message'])

In [4]:
Data.head()

Classification                                            Message
0            ham  Go until jurong point, crazy.. Available only ...
1            ham                      Ok lar... Joking wif u oni...
2           spam  Free entry in 2 a wkly comp to win FA Cup fina...
3            ham  U dun say so early hor... U c already then say...
4            ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
Data['Classification'].value_counts()

ham     4825
spam     747
Name: Classification, dtype: int64

In [6]:
Data.shape

(5572, 2)

In [7]:
# Get the stopwords
stopwords = nltk.corpus.stopwords.words('english')

In [9]:
def clean_text(text):
    print(text)
    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [ps.stem(word) for word in tokens if word not in stopwords]
    return text

In [48]:
#sen = ''
#[word.lower() for word in text if word not in string.punctuation]

NameError: name 'text' is not defined

In [14]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
ps=nltk.PorterStemmer()
tfidf_vect = TfidfVectorizer(analyzer=clean_text)
X_tfidf = tfidf_vect.fit_transform(Data['Message'])

In [15]:
X_tfidf

<5572x8109 sparse matrix of type '<class 'numpy.float64'>'
	with 50185 stored elements in Compressed Sparse Row format>

In [16]:
X_features = pd.DataFrame(X_tfidf.toarray())

In [17]:
X_features.head()

0     1     2     3     4     5     6     7     8     9     ...  8099  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

   8100  8101  8102  8103  8104  8105  8106  8107  8108  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 8109 columns]

In [18]:
feauture_name = tfidf_vect.get_feature_names()
pd.DataFrame(X_tfidf.toarray(), columns = feauture_name)

0  008704050406  0089mi  0121  01223585236  01223585334  \
0     0.0  0.0           0.0     0.0   0.0          0.0          0.0   
1     0.0  0.0           0.0     0.0   0.0          0.0          0.0   
2     0.0  0.0           0.0     0.0   0.0          0.0          0.0   
3     0.0  0.0           0.0     0.0   0.0          0.0          0.0   
4     0.0  0.0           0.0     0.0   0.0          0.0          0.0   
...   ...  ...           ...     ...   ...          ...          ...   
5567  0.0  0.0           0.0     0.0   0.0          0.0          0.0   
5568  0.0  0.0           0.0     0.0   0.0          0.0          0.0   
5569  0.0  0.0           0.0     0.0   0.0          0.0          0.0   
5570  0.0  0.0           0.0     0.0   0.0          0.0          0.0   
5571  0.0  0.0           0.0     0.0   0.0          0.0          0.0   

      0125698789   02  020603  ...  zindgi  zoe  zogtoriu  zoom  zouk  zyada  \
0            0.0  0.0     0.0  ...     0.0  0.0       0.0   0.0   0.0    0.0   
1            0.0  0.0     0.0  ...     0.0  0.0       0.0   0.0   0.0    0.0   
2            0.0  0.0     0.0  ...     0.0  0.0       0.0   0.0   0.0    0.0   
3            0.0  0.0     0.0  ...     0.0  0.0       0.0   0.0   0.0    0.0   
4            0.0  0.0     0.0  ...     0.0  0.0       0.0   0.0   0.0    0.0   
...          ...  ...     ...  ...     ...  ...       ...   ...   ...    ...   
5567         0.0  0.0     0.0  ...     0.0  0.0       0.0   0.0   0.0    0.0   
5568         0.0  0.0     0.0  ...     0.0  0.0       0.0   0.0   0.0    0.0   
5569         0.0  0.0     0.0  ...     0.0  0.0       0.0   0.0   0.0    0.0   
5570         0.0  0.0     0.0  ...     0.0  0.0       0.0   0.0   0.0    0.0   
5571         0.0  0.0     0.0  ...     0.0  0.0       0.0   0.0   0.0    0.0   

        é        ü  üll  〨ud  
0     0.0  0.00000  0.0  0.0  
1     0.0  0.00000  0.0  0.0  
2     0.0  0.00000  0.0  0.0  
3     0.0  0.00000  0.0  0.0  
4     0.0  0.00000  0.0  0.0  
...   ...      ...  ...  ...  
5567  0.0  0.00000  0.0  0.0  
5568  0.0  0.33524  0.0  0.0  
5569  0.0  0.00000  0.0  0.0  
5570  0.0  0.00000  0.0  0.0  
5571  0.0  0.00000  0.0  0.0  

[5572 rows x 8109 columns]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X_features, Data['Classification'], 
                                                    train_size = 0.8, random_state = 123)

In [23]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(4457, 8109)
(4457,)
(1115, 8109)
(1115,)


In [24]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200, n_jobs = -1)
rf_mdl = rf.fit(X_train, y_train)

In [25]:
y_pred = rf_mdl.predict(X_test)

In [27]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.99       962
        spam       1.00      0.81      0.90       153

    accuracy                           0.97      1115
   macro avg       0.99      0.91      0.94      1115
weighted avg       0.97      0.97      0.97      1115



In [32]:
confusion_matrix(y_test, y_pred)

array([[962,   0],
       [ 29, 124]], dtype=int64)

In [33]:
y_pred_train = rf_mdl.predict(X_train)

In [38]:
### Logistic Regression
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LogRegModel = LR.fit(X_train, y_train)

In [40]:
y_pred = LogRegModel.predict(X_test)

In [46]:
print("=====Classification Report for Test Data with Logistic Regression ==================")
print(classification_report(y_test, y_pred))
print("=====Confusion Matrix for Test Data with Logistic Regression========================")
print(confusion_matrix(y_test, y_pred))

=====Classification Report for Test Data with Logistic Regression ==================
              precision    recall  f1-score   support

         ham       0.95      1.00      0.97       962
        spam       0.98      0.67      0.79       153

    accuracy                           0.95      1115
   macro avg       0.97      0.83      0.88      1115
weighted avg       0.95      0.95      0.95      1115

=====Confusion Matrix for Test Data with Logistic Regression========================
[[960   2]
 [ 51 102]]


In [43]:
y_pred_train = rf_mdl.predict(X_train)

In [47]:
print("=====Classification Report for Train Data with Logistic Regression ==================")
print(confusion_matrix(y_train, y_pred_train))
print("=====Confusion Matrix for Train Data with Logistic Regression========================")
print(classification_report(y_train, y_pred_train))

=====Classification Report for Train Data with Logistic Regression ==================
[[3863    0]
 [   0  594]]
=====Confusion Matrix for Train Data with Logistic Regression========================
              precision    recall  f1-score   support

         ham       1.00      1.00      1.00      3863
        spam       1.00      1.00      1.00       594

    accuracy                           1.00      4457
   macro avg       1.00      1.00      1.00      4457
weighted avg       1.00      1.00      1.00      4457

